### ISSUE TITLE
day00 automated function to install Python

### ISSUE THREAD

**Issue by Medno** [42-AI/bootcamp_python#69] opened 2020-01-13 10:51 UTC
* Day: 00
* Exercise: 00

Hi,
In the Conda automated install topic, there is this line :
```
echo "export PATH=$MINICONDA_PATH:$PATH" >> ~/.zshrc
```
The thing is that if you have a **PATH** like:
```
/bar:/my/folder/with space/:/foo
```
the sourcing will fail because of invalid format of the variable (it expands environment variable).
Replacing double quotes with single should resolve this issue.

Hope it helps !

Edit:
My bad, it creates other issues.

But escaping the $ of $PATH should resolve the issue.

**Comment by fxbabin** [comment] 2020-01-28 10:53
@Medno i tried to modify the script to make an install in a directory with spaces but the installation just won't happen (the miniconda script refuse installation with spaces). I tried to previously export a directory with spaces but no bug appeared. I just can't reproduce the bug. Adding a `\` is not a problem but i want to ensure there is a bug in the first place.

Can we precise the steps needed to reproduce the bug ?

**Comment by Medno** [comment] 2020-01-28 12:33
For example, my PATH is composed by:

```.../sbin:/Applications/VMware Fusion.app/Contents/Public/:...```

When I launch the automated script as it is, I get this message:
```
~/.zshrc:export:110: not valid in this context: Fusion.app/Contents/Public/:...
```

So conda will be on the PATH and we have python with the correct version. But the PATH exported is broken.
This comes from the fact that the double quotes in the script expands the PATH variable in the zshrc during the ```echo "export PATH=$MINICONDA_PATH..."``` line in set_conda function.

Then in the zshrc we got something like:

```
export PATH=/path:/folder/with space/foo:bar
```

And the environment's PATH is splitted because of this space.

**Comment by fxbabin** [comment] 2020-01-28 13:29
ok, the bug will be fixed (i'm going to do a PR)

**Closed** 2020-02-03 14:33 UTC
Labels: fixme
