### ISSUE TITLE
PDFbuilder bug

### ISSUE THREAD

**Issue by AdrienVAR** [42-AI/bootcamp_python#47] opened 2019-10-24 11:28 UTC
In the outputs:
>>> npc.from_iterable(range(5)) should be on a new line

**Comment by Talasta** [comment] 2019-10-25 14:23
The problem is linked to the PDF builder, it does not handle well `<` chars.
I change the tag to fix this later.

**Comment by Talasta** [comment] 2019-11-26 09:35
closing, has been updated in the pdfbuilder repo

**Closed by Talasta** 2019-11-26 09:35 UTC
Labels: later
